name: build 
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build-wasm: 
    name: build-wasm
    runs-on: ubuntu-latest
    container: tipibuild/tipi-ubuntu
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: nxxm builds project 
        run: |
          tipi . --dont-upgrade --verbose

  build-linux: 
    name: build-linux
    runs-on: ubuntu-latest
    container: tipibuild/tipi-ubuntu

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: nxxm builds project 
        run: |
          tipi . --dont-upgrade --verbose -t gcc-7-cxx17 --test all 
